# ===================================
#  Form Behavior Config
# ===================================

name: winter.blog::lang.blog.create_category
form: ~/plugins/torus/blog/models/category/fields.yaml
modelClass: Torus\Blog\Models\Category
defaultRedirect: torus/blog/categories

create:
    redirect: torus/blog/categories/update/:id
    redirectClose: torus/blog/categories

update:
    redirect: torus/blog/categories
    redirectClose: torus/blog/categories
