# ===================================
#  Form Behavior Config
# ===================================

name: winter.blog::lang.blog.create_post
form: ~/plugins/torus/blog/models/post/fields.yaml
modelClass: Torus\Blog\Models\Post
defaultRedirect: torus/blog/posts

create:
    redirect: torus/blog/posts/update/:id
    redirectClose: torus/blog/posts

update:
    redirect: torus/blog/posts
    redirectClose: torus/blog/posts
