# ===================================
#  Import/Export Behavior Config
# ===================================

import:
    # Page title
    title: winter.blog::lang.posts.import_post

    # Import List Column configuration
    list: $/torus/blog/models/postimport/columns.yaml

    # Import Form Field configuration
    form: $/torus/blog/models/postimport/fields.yaml

    # Import Model class
    modelClass: Torus\Blog\Models\PostImport

    # Redirect when finished
    redirect: torus/blog/posts

    # Required permissions
    permissions: winter.blog.access_import_export

export:
    # Page title
    title: winter.blog::lang.posts.export_post

    # Output file name
    fileName: posts.csv

    # Export List Column configuration
    list: $/torus/blog/models/postexport/columns.yaml

    # Export Model class
    modelClass: Torus\Blog\Models\PostExport

    # Redirect when finished
    redirect: torus/blog/posts

    # Required permissions
    permissions: winter.blog.access_import_export
